### ISSUE TITLE
saphyra.py

### ISSUE THREAD

**Issue by moinak-kalilinux** [H1R0GH057/Anonymous#12]
Starting the Attack
ANONYMOUS
Traceback (most recent call last):
  File "saphyra.py", line 3527, in <module>
    host = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

What's happening here?

**Comment by sambatlim** [comment]
check this: #13

**Comment by ghost** [comment]
You supplied a https:// website, saphyra (and most other tools here) only work with http://

**Comment by Nanostar007** [comment]
File "/home/kali/saphyra.py", line 1773
    headers_useragents.append('Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.3) Gecko/20090913 Firefox/3.5.3')
TabError: inconsistent use of tabs and spaces in indentation
Can someone pls explain this error to me?

**Comment by 2icm** [comment]
Am facing same error. i think this py script is TRASH
